complete -f -c flutter -n '__fish_use_subcommand' -a 'analyze' -d 'Analyze the project\'s Dart code.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'assemble' -d 'Assemble and build Flutter resources.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'attach' -d 'Attach to a running app.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'bash_completion' -d 'Output command line shell completion setup scripts.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'build' -d 'Build an executable app or install bundle.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'channel' -d 'List or switch Flutter channels.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'clean' -d 'Delete the build/ and .dart_tool/ directories.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'config' -d 'Configure Flutter settings.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'create' -d 'Create a new Flutter project.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'devices' -d 'List all connected devices.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'doctor' -d 'Show information about the installed tooling.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'downgrade' -d 'Downgrade Flutter to the last active version for the current channel.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'drive' -d 'Run integration tests for the project on an attached device or emulator.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'emulators' -d 'List, launch and create emulators.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'format' -d 'Format one or more Dart files.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'gen_l10n' -d 'Generate localizations for the current project.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'install' -d 'Install a Flutter app on an attached device.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'logs' -d 'Show log output for running Flutter apps.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'precache' -d 'Populate the Flutter tool\'s cache of binary artifacts.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'pub' -d 'Commands for managing Flutter packages.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'run' -d 'Run your Flutter app on an attached device.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'screenshot' -d 'Take a screenshot from a connected device.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'symbolize' -d 'Symbolize a stack trace from an AOT-compiled Flutter app.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'test' -d 'Run Flutter unit tests for the current project.'
complete -f -c flutter -n '__fish_use_subcommand' -a 'upgrade' -d 'Upgrade your copy of Flutter.'